# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  config.vm.box = "ubuntu-14.04"
  config.vm.network :private_network, ip: "192.168.55.55"
  config.vm.network :forwarded_port, guest: 80, host: 8888
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  config.vm.network :forwarded_port, guest: 9200, host: 9200

  config.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.synced_folder "nginx/", "/home/vagrant/synced/nginx", create: true
  config.vm.provision "docker" do |docker|
    docker.build_image "/home/vagrant/synced/nginx", args: "-t seizans/nginx"
    docker.run "seizans/nginx", args: "-P"
  end
end
